name: Docker

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  VERSION: 6.0.7.1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - self-hosted
        include:
          - runner: self-hosted
            arch: arm64
          - runner: ubuntu-latest
            arch: amd64

    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          version: latest
          platforms: linux/${{ matrix.arch }}

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 726418723176.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.LR_PRD_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.LR_PRD_AWS_SECRET_ACCESS_KEY }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: 726418723176.dkr.ecr.us-east-1.amazonaws.com/sendy:${{ github.sha }}-${{ matrix.arch }}

  image_manifest:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch the whole repo history

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          version: latest

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 726418723176.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.LR_PRD_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.LR_PRD_AWS_SECRET_ACCESS_KEY }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            726418723176.dkr.ecr.us-east-1.amazonaws.com/sendy
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha,prefix=,format=short
            type=raw,value=${{ env.VERSION }},enable={{ is_default_branch }}

      - name: Create Image Manifest
        run: |
          docker buildx imagetools create -t ${{ join(fromJSON(steps.meta.outputs.json).tags, ' -t ') }} 726418723176.dkr.ecr.us-east-1.amazonaws.com/sendy:${{ github.sha }}-amd64 726418723176.dkr.ecr.us-east-1.amazonaws.com/sendy:${{ github.sha }}-arm64